def generate_report(screenshot_type, summary, info, extracted_text):

    report = f"""
=============================
        SnapSense AI
=============================

Screenshot Type
-----------------------------
{screenshot_type}

AI Summary
-----------------------------
{summary}

Important Information
-----------------------------

Emails:
{', '.join(info['emails']) if info['emails'] else 'None'}

Phone Numbers:
{', '.join(info['phones']) if info['phones'] else 'None'}

Dates:
{', '.join(info['dates']) if info['dates'] else 'None'}

Websites:
{', '.join(info['websites']) if info['websites'] else 'None'}

Amounts:
{', '.join(info['amounts']) if info['amounts'] else 'None'}

OCR Text
-----------------------------
{extracted_text}

=============================
Generated by SnapSense AI
=============================
"""

    return report